[tools]
uv = "latest"
task = "latest"
pnpm = "latest"
node = "22"
starship = "latest"
ghq = "latest"
lazygit = "latest"
lefthook = "latest"
fzf = "latest"
neovim = "latest"

[settings]
# For exclude .python-version
idiomatic_version_file_enable_tools = []
