[server]
name = "atskkserv"
cli_options = [
    "serve",
    "--server-host=0.0.0.0",
    "{root}/var/SKK-JISYO.utf-8",
]

[server.windows]
taskdef_path = "{root}/var/taskdef.xml"

[dictionary]
filepath = "{root}/var/SKK-JISYO.utf-8"
cli_options = [
]

[[dictionary.sources]]
filepath = "{root}/var/dict/SKK-JISYO.L"
url = "https://skk-dev.github.io/dict/SKK-JISYO.L.gz"
options = { filetype = "gzip" }
