---
# ------
# Symlink targets of files in `./root`.a
# ------
links:
  # nushell
  - source: 'app/Nushell'
    targets:
      Windows_NT: '{{APPDATA}}\nushell'
      Linux: '{{HOME}}/.config/nushell'
      Darwin: '{{HOME}}/.config/nushell'
  # WezTerm
  - source: 'app/WezTerm'
    targets:
      Windows_NT: '{{USERPROFILE}}\.config\wezterm'
      Linux: '{{HOME}}/.config/wezterm'
      Darwin: '{{HOME}}/.config/wezterm'
  # uv
  - source: 'root/.config/uv'
    targets:
      Windows_NT: '{{USERPROFILE}}\.config\uv'
      Linux: '{{HOME}}/.config/uv'
      Darwin: '{{HOME}}/.config/uv'
  # alacritty
  - source: 'app/Alacritty'
    targets:
      Windows_NT: '{{APPDATA}}\alacritty'
      Linux: '{{HOME}}/.config/alacritty'
      Darwin: '{{HOME}}/.config/alacritty'
  # Starship
  - source: 'root/.config/starship.toml'
    targets:
      Windows_NT: '{{USERPROFILE}}\.config\starship.toml'
      Linux: '{{HOME}}/.config/starship.toml'
      Darwin: '{{HOME}}/.config/starship.toml'
  - source: 'root/.config/sheldon'
    targets:
      Linux: '{{HOME}}/.config/sheldon'
      Darwin: '{{HOME}}/.config/sheldon'
  # NeoVim
  - source: 'root/.config/nvim'
    targets:
      Windows_NT: '{{USERPROFILE}}\AppData\Local\nvim'
      Linux: '{{HOME}}/.config/nvim'
      Darwin: '{{HOME}}/.config/nvim'
  # GitTui
  - source: 'root/.config/gitui'
    targets:
      # TODO: Configure for Windows
      Linux: '{{HOME}}/.config/gitui'
      Darwin: '{{HOME}}/.config/gitui'
  # Rio
  - source: 'app/Rio'
    targets:
      Windows_NT: '{{USERPROFILE}}\AppData\Local\rio'
  # Zed
  - source: 'app/Zed'
    targets:
      Windows_NT: '{{APPDATA}}\Zed'
      Linux: '{{HOME}}/.config/zed'
      Darwin: '{{HOME}}/.config/zed'
uv-tools:
  - 'esbonio@1.0.0'
  - 'ty@0.0.1a25'
  - 'ruff@0.14.6'
bun-tools:
  - '@anthropic-ai/claude-code@2.1.14'
