[[links]]
source = 'root/.config/mise'

[links.targets]
Windows_NT = '{{USERPROFILE}}\.config\mise'
Linux = '{{HOME}}/.config/mise'

[[links]]
source = 'root/.config/nushell'

[links.targets]
Windows_NT = '{{APPDATA}}\nushell'
Linux = '{{HOME}}/.config/nushell'

[[links]]
source = 'root/.config/wezterm'

[links.targets]
Windows_NT = '{{USERPROFILE}}\.config\wezterm'
Linux = '{{HOME}}/.config/wezterm'

[[links]]
source = 'root/.config/uv'

[links.targets]
Windows_NT = '{{USERPROFILE}}\.config\uv'
Linux = '{{HOME}}/.config/uv'

[[links]]
source = 'root/.config/alacritty'

[links.targets]
Windows_NT = '{{APPDATA}}\alacritty'
Linux = '{{HOME}}/.config/alacritty'

[[links]]
source = 'root/biome.jsonc'

[links.targets]
Windows_NT = '{{USERPROFILE}}\biome.jsonc'
Linux = '{{HOME}}/biome.jsonc'

[[links]]
source = 'root/.harper-dict.txt'

[links.targets]
Windows_NT = '{{USERPROFILE}}\.harper-dict.txt'
Linux = '{{HOME}}/.harper-dict.txt'

[[links]]
source = 'root/.config/starship.toml'

[links.targets]
Windows_NT = '{{USERPROFILE}}\.config\starship.toml'
Linux = '{{HOME}}/.config/starship.toml'

[[links]]
source = 'root/.zshenv'

[links.targets]
Linux = '{{HOME}}/.zshenv'

[[links]]
source = 'root/.zshrc'

[links.targets]
Linux = '{{HOME}}/.zshrc'
