version: '3'

includes:
  root:
    taskfile: ./root
    flatten: true

tasks:
  update:
    desc: 'Update env'
    dotenv:
      - '.env'
    cmds:
      - 'git pull'
      - 'aqua i'
      - 'nu scripts/setup.nu'
      - 'nu scripts/sync-uv-tools.nu'
      - 'nu scripts/sync-bun-tools.nu'
      - |
        if [ "$USE_NIMBLE" = "1" ]; then
          nimble build
        fi
  zed-push:
    desc: 'Push Zed settings'
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - >
        {{.ZED_SYNC_SETTINGS}}
        --exclude=wsl_connections
        ./root/.config/zed/settings.base.json
        ./root/.config/zed/settings.json
  zed-pull:
    desc: 'Pull Zed settings'
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - >
        {{.ZED_SYNC_SETTINGS}}
        --exclude=wsl_connections
        ./root/.config/zed/settings.json
        ./root/.config/zed/settings.base.json

vars:
  ZED_SYNC_SETTINGS:
    sh: |
      if [ -f .bin/zed-settings ]; then
        echo ".bin/zed-settings"
      elif [ -f .bin/zed-settings.exe ]; then
        echo ".bin/zed-settings.exe"
      else
        echo "uv run scripts/zed-settings.py"
      fi
