[server]
dict_path = "{root}/var/dict.yaskkserve2"
cli_options = [
    "--google-suggest",
]

[dictionary]
output = "{root}/var/dict.yaskkserve2"
cli_options = [
    "--verbose",
]

[[dictionary.sources]]
filepath = "{root}/var/dict/SKK-JISYO.L"
url = "https://skk-dev.github.io/dict/SKK-JISYO.L.gz"
options = { filetype = "gzip" }
