# ------
# Tasks to manage global applications by aqua.
# ------
version: '3'

tasks:
  create-dictionary:
    desc: 'Add global application.'
    cmds:
      - 'uv run ./scripts/create-dictionary.py ./settings.toml'
  test-server:
    desc: 'Run serfer for testing.'
    cmd: 'yaskkserv2 --google-suggest var/dict.yaskkserv2 {{.CLI_ARGS}}'
