# ------
# Global taskfile
#
# This manages wrapper scripts (e.g. deno cli)
# ------

version: '3'

tasks:
  webserver:
    desc: 'Run static web server'
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      ROOT_DIR: '{{index .CLI_ARGS_LIST 0}}'
      PORT: '{{if gt (len .CLI_ARGS_LIST) 1}}{{index .CLI_ARGS_LIST 1}}{{else}}8000{{end}}'
    cmds:
      - 'uv run python -m http.server -d {{.ROOT_DIR}} {{.PORT}}'
  claude:
    desc: 'Run Claude Code'
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - 'bun x @anthropic-ai/claude-code@{{.VERSION}} {{.CLI_ARGS }}'
    vars:
      VERSION: '{{ env "TASK_X_CLAUDE_CODE_VERSION" | default "1.0.51" }}'
  ccusage:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - 'bun x ccusage {{.CLI_ARGS}}'
  gemini:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - 'bun x @google/gemini-cli {{.CLI_ARGS}}'
