[general]
live_config_reload = true

[window]
dimensions = { columns = 140, lines = 40}
opacity = 0.8

[font]
normal = {family = "HackGen Console NF"}
size = 12

[terminal]
shell = "nu"

[keyboard]
bindings = [
  {key="N", mods = "Control | Shift", action = "CreateNewWindow"},
  # {key="T", mods = "Control | Shift", action = "CreateNewTab"},
]
