name: Continuous Integration

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.51.2
      - name: Set up workspace
        run: |
          uv sync --dev --all-extras
      - name: Lint by lefthook
        run: |
          lefthook run pre-commit --all-files
